### ISSUE TITLE
[FEATURE] Provider should take configuration from the CLI config (~/.civo.json)

### ISSUE THREAD

**Issue by fernando-villalba** [civo/terraform-provider-civo#246]
## Issue

When the CLI is configured with a token, terraform should automatically take the token config from the cli config file at from `~/.civo.json`

Alternatively (or preferentially) it can be taken from the environment variable as it is possible to do now.

We should dissuade users from providing credentials via an input variable. These should be strictly reserved for short lived tokens which we don’t have now.

## Acceptance Criteria

* By default, when no token input  or token environment variable is provided, it should be fetch the credentials from the CLI at path `~/.civo.json`
* We should not have a `token` input, the token should never be entered as variable or input that gets saved on state. Instead change this to `credentials_file` or something like that where the user can specify the location of a file with the token.
* The priority of configuration should be the following Environment variable --> credentials file path configured in input --> CLI config path

**Comment by Praveen005** [comment]
**Proposed Approach for #246:**

Hi Team,

I have been working on the feature request outlined in issue #246. I kindly request your review and feedback.

Here is what I have done:

1. Removed the `civo_token` field from the provider schema and replaced it with a `credential_file` option.
2. Implemented a priority-based token retrieval:
          1. Environment variable (`CIVO_TOKEN`).
          2. Token provided via a Credential file.
          3. Lastly, fall back to CLI config file (~/.civo.json)

3. Added a `getToken` function to handle the token retrieval logic.
4. Implemented `readTokenFromFile` to securely read tokens from JSON files.
5. One additional thing that I have added is, the user can set the Credential file path in `CIVO_CREDENTIAL_FILE` environment variable as well. For this I took inspiration from [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/9f5b94e8eaa9a3826eeb9c48a0cea32ae25a6871/internal/provider/provider.go#L227)

5. Updated and expanded test cases to cover:
         1. Reading token from environment variable
         2. Reading token from a specified credentials file
         3. Falling back to the CLI config file


6. Updated the [example](https://registry.terraform.io/providers/civo/civo/latest/docs) in `provider.tf` to use the new `credential_file` option instead of `civo_token`.

**The concerned code can be found in the gist [here](https://gist.github.com/Praveen005/eabe81a92b6d679172701fe030f667b4).**

**Screenshots:**

It passes all the tests:

<img width="639" alt="Screenshot 2024-07-08 121905" src="https://github.com/civo/terraform-provider-civo/assets/42026111/95802175-6586-4f55-83d7-f224e023455c">


Test Coverage:

<img width="746" alt="Screenshot 2024-07-08 121955" src="https://github.com/civo/terraform-provider-civo/assets/42026111/13fcb0ce-ca90-42d4-bad6-92a99111dc4f">


Thank you for your time and feedback.

Best regards,

Praveen

**Comment by uzaxirr** [comment]
Hey @Praveen005 
Thank you for your amazing diagnosis, this approach looks fine to me can you go ahead and raise a PR.
Please do test it locally and attach Screenshots in the PR

**Comment by uzaxirr** [comment]
Closed via: https://github.com/civo/terraform-provider-civo/pull/248
