### ISSUE TITLE
[BUG] reserve_ipv4 field in civo_instance reverts to ip when id is specified

### ISSUE THREAD

**Issue by fernando-villalba** [civo/terraform-provider-civo#250]
## Issue

```hcl

provider "civo" {
  # token = var.civo_token
  region = "LON1"
}

resource "civo_reserved_ip" "www" {
    name = "test-ip2" 
}


resource "civo_instance" "foo" {
    hostname = "amazingthingy20"
    tags = ["python", "nginx"]
    notes = "This is a test-issue"
    size = "g3.xsmall"
    region = "LON1"
    reserved_ipv4 = civo_reserved_ip.www.id
    firewall_id = "default-default"
    disk_image = "debian-10"
}
```

Every time you reapply this code it will continuously "update" the reserve_ipv4 field from id to ip:

<img width="989" alt="image" src="https://github.com/civo/terraform-provider-civo/assets/15110153/a30ab55a-db4d-461f-82c4-5f09b5eef7ba">

## Acceptance criteria

* We should perhaps ask for either ip or id for the `reserved_ipv4` field, not both. But if you do both, you need to ensure that this does not happen. 
* Requesting id or name, may be better than asking for the actual ip.

**Comment by Praveen005** [comment]
Hi @uzaxirr 

Sorry, it took me a while to figure out but I believe this approach resolves the issue. I kindly request a review.

**Current state:**

The issue is happening during the creation phase, updates are going through as intended.

1. `main.tf`

<img width="355" alt="Screenshot 2024-07-24 172532" src="https://github.com/user-attachments/assets/51a09cd3-4ceb-4f8a-87b3-6dbd287e17c3">

2. Instance does get created but `reserved_ipv4` instead of storing the `ip` it stores `id`

<img width="375" alt="Screenshot 2024-07-24 172557" src="https://github.com/user-attachments/assets/36bef568-f957-4e90-8799-a22512d0249f">

3. Debug log shows a Warning:

<img width="868" alt="Screenshot 2024-07-24 172628" src="https://github.com/user-attachments/assets/13ab5825-7f37-4c37-8c21-d31c9266f326">

4. Reason for this warning: `reserved_ipv4` is being set equal to `ReservedIPID` despite `main.tf` asking an `ip` to be stored.

 [`d.Set("reserved_ipv4", resp.ReservedIPID)` ](https://github.com/civo/terraform-provider-civo/blob/c9b61643378f97130d56aae00999e68168192bcd/civo/instances/resource_instance.go#L377)

5. How did I conclude, that the warning is because of the above said reason?

: Because, when we set it to store `ip` like below, the warning vanishes.

<img width="320" alt="Screenshot 2024-07-24 172748" src="https://github.com/user-attachments/assets/2e07e2b6-d30f-4f7a-b8a3-9aa57a88a2d9">

6. At this point, one thing is clear, that terraform knows that, `instance_reserved_ipv4`'s value was to be set to `ip` but `id` is being stored and vice-versa.

So, if we somehow get to know what needs to be stored, we can set the value of `reserved_ipv4` accordingly. And we can do that the following way in `resourceInstanceRead()`:

```
if d.HasChange("reserved_ipv4"){
		_, new := d.GetChange("reserved_ipv4")
		newValue := new.(string)
		d.Set("reserved_ipv4", newValue)
}
```
if `main.tf` has `reserved_ipv4 = civo_reserved_ip.www.id`, `newValue` will have the `id`.
else if `main.tf` has `reserved_ipv4 = civo_reserved_ip.www.ip`, `newValue` will have the `ip`.

**Post code changes:**

`main.tf`:

<img width="345" alt="Screenshot 2024-07-24 191136" src="https://github.com/user-attachments/assets/8c822e2b-0c0a-48a0-b646-31399343316c">

Successful resource creation:

<img width="376" alt="Screenshot 2024-07-24 191451" src="https://github.com/user-attachments/assets/e5977cd3-0493-42e1-a3fd-5670dbdd2e03">

Updated `main.tf`:

<img width="342" alt="Screenshot 2024-07-24 191615" src="https://github.com/user-attachments/assets/48af82d7-c604-4304-a8f1-db2b1bbbec98">


Re-applying isn't causing any hiccups, it is correctly changing from `id` to `ip`

<img width="482" alt="Screenshot 2024-07-24 191412" src="https://github.com/user-attachments/assets/860c2d38-02a3-46e7-ab8e-387efad2c976">

<img width="351" alt="Screenshot 2024-07-24 191429" src="https://github.com/user-attachments/assets/32e147d6-ee01-4d82-bb13-68137671d890">

Re-applying for the second time: No Issues!

<img width="340" alt="Screenshot 2024-07-24 190915" src="https://github.com/user-attachments/assets/48f25766-681a-444b-a857-4e6f2e8a1a15">

**Comment by uzaxirr** [comment]
hii @Praveen005 the above approach seems reasonable, can you please raise a PR
