### ISSUE TITLE
[BUG] Show database PrivateIP

### ISSUE THREAD

**Issue by vishalanarase** [civo/terraform-provider-civo#332]
### Description

* Show the database PricateIP field
* Civogo is returning in the response

### Acceptance Criteria

show database PrivateIP

**Comment by Praveen005** [comment]
Hi @uzaxirr,

Hope you are doing fine.

For this issue, I updated the `civogo` dependency from `v0.3.73` to the most recent `v0.3.75`, since `privateIPv4` field was added recently.

Missing `private_ip` field:

<img width="434" alt="Screenshot 2024-09-01 220144" src="https://github.com/user-attachments/assets/b85127b3-4e10-44dd-8904-424d243a1a6c">

post that, I added a `private_ip` field to the resource schema, and set its value in the `resourceDatabaseRead` function, and with this `private_ip` gets correctly reflected in the terraform state.

<img width="384" alt="Screenshot 2024-09-02 104903" src="https://github.com/user-attachments/assets/74229501-055b-4fc5-9df5-79c04f7394ec">

<br>

<img width="247" alt="Screenshot 2024-09-02 104919" src="https://github.com/user-attachments/assets/93f6131f-ea50-4a7a-93af-14148b437c59">

-----------------------------------------------------------------------------------
**Result:**

Before:

No `private_ip` in the terraform state:

<img width="404" alt="Screenshot 2024-09-01 224924" src="https://github.com/user-attachments/assets/df1f68ed-51ba-4b0b-99a0-734025106c54">

After:

Correctly getting reflected during plan phase:

<img width="291" alt="Screenshot 2024-09-01 233912" src="https://github.com/user-attachments/assets/6395b5a5-81d0-4000-899d-932bbd996c65">

`private_ip` having an IP assigned post creation:

<img width="409" alt="Screenshot 2024-09-01 234441" src="https://github.com/user-attachments/assets/25a58159-d3de-47de-9606-be066805ccaf">

**Comment by uzaxirr** [comment]
Hiii @Praveen005 
i already have a PR raised for this: https://github.com/civo/terraform-provider-civo/pull/333
forgot to link my bad

**Comment by Praveen005** [comment]
I see! I'll make sure to check for existing PRs next time. Thank you @uzaxirr
